version: '3.8'
services:
  web-app:
    build: ./web-app
    ports:
      - "8080:3000"
    networks:
      - my-network

  alpine:
    image: alpine
    networks:
      - my-network
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
    depends_on:
      - web-app

networks:
  my-network: